user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  gravatar_size:
    default: 80
  remember:
    true?: 1
  hours:
    max: 2
  url:
    gravatar: "https://secure.gravatar.com/avatar/"
  per_page:
    size: 4
  gravatar:
    size: 50
admin:
  email:
    default: "trungngo1996dn@gmail.com"
microposts:
  content:
    max_length: 140
  gravatar_size:
    default: 50
  picture:
    size: 5
